name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      run: |
          echo ${{ github.token }}
          echo ${{ secrets.GITHUB_TOKEN }}
